<?php

/**
 * @file
 *
 */


/**
 * Implementation of hook_entity_info_alter()
 */
function hot_secondary_touts_entity_info_alter(&$entity_info) {
  // Fieldable panel pane bundle to support call-to-action
  $entity_info['fieldable_panels_pane']['bundles']['hot_secondary_touts'] = array(
    'label' => t('Secondary Tout'),
    'pane category' => t('HotWidgets!'),
    'pane top level' => FALSE,
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_image.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/hot_secondary_touts',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}


/**
 * Implements hook_theme().
 */
function hot_secondary_touts_theme(){
  return array(
    'fieldable_panels_pane__hot_secondary_touts' => array(
      'template' => 'templates/fieldable-panels-pane--hot-secondary-touts',
      'render element' => 'elements',
      'type' => 'module'
    )
  );
}


/**
 * Implements hook_preprocess_fieldable_panels_panes().
 */

function hot_secondary_touts_preprocess_fieldable_panels_pane(&$variables){
  if($variables['elements']['#bundle'] === 'hot_secondary_touts'):
  $link = $variables['content']['field_basic_link'][0];
  if(isset($variables['content']['field_basic_icon'][0])){
    $link['#element']['title'] .= ' ' . render($variables['content']['field_basic_icon'][0]);
  }

  $link['#element']['attributes'] = array(
    'class' => 'secondary-tout '
  );

  if(isset($variables['field_hot_styles'])){
    $link['#element']['attributes']['class'].=
       'secondary-tout-' . $variables['field_hot_styles'][0]['value'];
  }
  $variables['content']['field_basic_link'][0] = $link;
  endif;
}
